set nocompatible
" colorscheme evening
syntax on
filetype on
set encoding=utf-8
set termencoding=utf-8
set fileencodings=ucs-bom,iso-2022-jp-3,iso-2022-jp,eucjp-ms,euc-jisx0213,euc-jp,sjis,cp932,utf-8
set fileencoding=utf-8
set history=50
set backspace=indent,eol,start
set showcmd
set incsearch
set hlsearch
set autoindent
set nu
set tabstop=8
set nowrap
set ruler
